config/routes.rb
Cookbook::Application.routes.draw do
  resources :sessions, :only => [:new, :create] 
  match "signup" => 'users#new', :as => "signup"
  match "login" => 'sessions#new', :as => "login"
  match "logout" => 'sessions#destroy', :as => "logout"

 
  resources :comments
  resources :steps
  resources :ingredients
  resources :categories
  resources :users, :only => [:new, :create]
  root :to => 'recipes#index'
  
  

  get "recipes/index"

  get "recipes/new" 
  post "recipes/create"
  
  get "recipes/change/:id" => 'recipes#edit', :as => :edit_recipe
  put "recipes/update/:id" => "recipes#update", :as => :update_recipe
    # put "recipesupdate/3"
    
  delete "recipes/destroy/:id" => "recipes#destroy",  :as => :delete_recipe
    
  get "recipe/:id" => "recipes#show", :as => :recipe  
  
  root :to => "recipes#index"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :title
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
     @recipe = Recipe.new(params[:recipe])
     
     @twilio_client.account.sms.messages.create(
             :from => '+14158675309',
             :to => '+14158675309',
             :body => "#{@recipe.title} was added successfully."
           )
    
      if @recipe.save
        redirect_to "/recipes/index"
      else
        render :new
      
      end
  end

   def update
      @recipe = Recipe.find(params[:id])

      if @recipe.update_attributes(params[:recipe])
        redirect_to "/recipes/index"
      else
        render :edit
        # In Sinatra, it would be `erb :edit`.
      end
    end

    def destroy
      @recipe = Recipe.find(params[:id])
      @recipe.destroy
      redirect_to "/recipes/index"
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/edit.html.erb
<h1>Recipes edit</h1>

<p>Find me in app/views/recipes/edit.html.erb</p>

<%= form_for @recipe, :url => {:action => "update"} do |f| %>
  <label>Title</label>
  <%= f.text_field :title %><br>

  <%= f.submit %>
<% end %>

app/views/recipes/index.html.erb
<h1>Recipes index</h1>



<% @recipes.each do |recipe| %>
  <p>
    <%= link_to recipe.title, recipe_path(recipe.id) %> |
    <%= link_to "Edit", edit_recipe_path(recipe.id) %> |
    <%= link_to "Delete", delete_recipe_path(recipe.id), :method => :delete %>
  </p>
<% end %>

app/views/recipes/new.html.erb
<h1>Recipes new</h1>
<p>Find me in app/views/recipes/new.html.erb</p>

<%= form_for @recipe, :url => {:action => "create"} do |f| %>
  <label>Title</label>
  <%= f.text_field :title %><br>

  <%= f.submit %>

<% end %>

app/views/recipes/show.html.erb
<h1>Recipes show</h1>

<h3><%= @recipe.title %></h3>